version: '3.8'

services:
  zhi_yuan_ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
